name = "OptimalTransportDataIntegration"
uuid = "f00d1d04-589e-4742-a825-5ec24d3c488e"
version = "0.1.2"
authors = ["Jeremy Omer <jeremy.omer@insa-rennes.fr>", "Valérie Garès <valerie.gares@insa-rennes.fr>", "Pierre Navaro <pierre.navaro@math.cnrs.fr>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PythonOT = "3c485715-4278-42b2-9b5f-8f00e43c12ef"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[sources]
PythonOT = {rev = "main", url = "https://github.com/pnavaro/PythonOT.jl"}

[compat]
Aqua = "0.8"
CSV = "0.10"
Clp = "1"
DataFrames = "1.6"
DelimitedFiles = "1.9"
Distances = "0.10"
Distributions = "0.25"
DocStringExtensions = "0.9"
Documenter = "1.8.0"
Flux = "0.14, 0.15, 0.16"
JSON = "0.21, 1"
JuMP = "1"
LinearAlgebra = "1"
OrderedCollections = "1.8.0"
PDMats = "0.11"
Parameters = "0.12"
Printf = "1"
PythonOT = "0.1.6"
Random = "1"
Statistics = "1"
StatsBase = "0.34.4"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "Documenter"]
